alert('¡Bienvenida y bienvenido a nuestro sitio web!');
let nombre_1 = "Lua";
let edad_1 = 25;
let numeroDeVentas = 50;
let saldoDisponible = 1000;
//alert('¡Error! Completa todos los campos');
let mensajeDeError = "¡Error! Completa todos los campos";
alert(mensajeDeError);
let nombre = prompt("Cual es tu nombre") ;
console.log(nombre);
let edad = prompt('ingresa tu edad ');
console.log(edad);